### ISSUE TITLE
Unknown Teamspeak Error

### ISSUE THREAD

**Issue by JonathanN1203** [Splamy/TS3AudioBot#791] opened 2020-05-09 20:41 UTC
Does somebody now why I get this error in the screen "WARN|24| Unknown Teamspeak Error. (Connection closed)"

**Comment by oscsystemx** [comment] 2020-05-10 12:50
![Screenshot_5](https://user-images.githubusercontent.com/48587121/81499684-6ce8e080-92f7-11ea-9d2b-a23ef7b62068.png)

**Comment by Splamy** [comment] 2020-05-10 13:56
Please use our [issue templates](https://github.com/Splamy/TS3AudioBot/issues/new/choose) and fill out all necessay information for us to know the context of the problem.

> **Version**
Which commit did you build or download? (dotnet TS3AudiBot.exe -V or !version in chat)

**Comment by JonathanN1203** [comment] 2020-05-10 16:09
I get this error in the screen "WARN|24| Unknown Teamspeak Error. (Connection closed)"

I only have started the bot and then it comes.

If I send the bot the message "!version" I get 
Version: <?>
Branch: <?>
CommitHash: <?>

I use it on an debian 10 with mono

The log says only "WARN|24| Unknown Teamspeak Error. (Connection closed)"

**Comment by Splamy** [comment] 2020-05-12 15:15
> Version: Branch:
CommitHash: <?>

Uhm, that doesn't help, which version did you download? master/develop ? And when? Did you try to update to the lastest version of the branch you downloaded?

Generally speaking the error might occour when a event tries to execute a command but the bot already disconnected.
If the bot didn't disconnect please give me more context what happened before as well as the log in the area before that.

**Comment by JonathanN1203** [comment] 2020-05-12 18:45
I downloaded the version on github and change something. What have I to change for the Update?

**Comment by Flakebi** [comment] 2020-05-12 18:52
I don’t understand your question but as you change code, you should really use git, it will make your life a lot easier.
https://help.github.com/en/github/getting-started-with-github/quickstart

**Comment by JonathanN1203** [comment] 2020-05-13 07:47
I only changed some messages.

**Comment by Splamy** [comment] 2020-05-19 13:24
Well to try get some useful information: Is there any behaviour pattern or certain commands which result in this happening? This error most likely comes about 15 after interacting, so a log with at least so much time before would be appreciated to diagnose the problem

**Comment by Flakebi** [comment] 2021-02-16 20:29
Closing because there is no way for us to reproduce or fix this. If there are still problems, please reopen or create a new issue.

**Closed** 2021-02-16 20:30 UTC
Labels: needs investigation
