### ISSUE TITLE
Command issue with multiple bots

### ISSUE THREAD

**Issue by MoroseCorpse** [Splamy/TS3AudioBot#672] opened 2019-11-06 14:37 UTC
I have the problem that if I have 2 bots running and both loaded the same plugin and a command to one of these two senders, then only the same bot executes the command. 

Example:
````
[Command("test")]
public void test(ClientCall client)
{
     string BotID = ConfBot.Name;
     FullClient.SendPrivateMessage("Dies ist nur ein test: " + BotID, client.ClientId.Value);
}
````
If I now send the command test to Bot1, then Bot1 also writes to me, but if I send the command to Bot2, Bot1 still writes to me. Also, the output name is only from the one bot that writes me. 
In my example, Bot1 is the bot that first connects and then Bot2 afterwards

Other things like events work fine with both bots separately. So the problem is only with commands.

I'm using this version: 
Version: 0.10.1+2
Branch: master
CommitHash: eb56a2f8f7e5fdc12a84294276b8ad5b3c6db3d4

**Comment by 07artem132** [comment] 2019-11-06 14:47
Hi, your question is a duplicate of mine: https://github.com/Splamy/TS3AudioBot/issues/670

**Comment by Splamy** [comment] 2019-11-06 15:13
Somewhat related, but not quite (@07artem132 I'll get to your problem shortly)

Your problem is, that your plugin gets a reference to the ts3client (`FullClient`) it was loaded for.
But you might notice that even though you loaded a BotPlugin (which should be local to each bot), the command is loaded for all bots.
This is because currently all bots share the same command tree. We haven't fixed that yet, but I'm currently working on it.

The fix in your case is quite simple, to get the ts3client object the command was called with make your function static (not necessary but recommended)
and get the reference to the ts3client object via parameter like this:

```cs
[Command("test")]
public static void test(Ts3Client ts3Client, ClientCall client)
{
     string BotID = ConfBot.Name;
     ts3Client.SendPrivateMessage("Dies ist nur ein test: " + BotID, client.ClientId.Value);
}
```

You could also consider a static plugin if you don't need local objects: https://github.com/Splamy/TS3AudioBot/wiki/Plugins#staticplugin

**Closed** 2019-11-16 19:46 UTC
Labels: question
