### ISSUE TITLE
About youtube search

### ISSUE THREAD

**Issue by farfik1** [Splamy/TS3AudioBot#980] opened 2022-04-14 04:08 UTC
Hello,

Can I write the code below in a file instead of writing it to the bot every time I create a bot?
Thus, when I create a bot, I want this command to be set.
What file can I write to? Or is there a Global command?

!alias add ytp "!x (!search from youtube (!param 0)) (!search play 0)"

**Comment by Splamy** [comment] 2022-04-19 11:38
Currently not, I originally planned to add alias merging between the `ts3audiobot.toml` and separate `bot.toml`s.
However since I started working on a fulltime job I don't have the free time to work on ts3ab that much anymore. So maybe in the far future I'll get to add new features again.

**Comment by Flakebi** [comment] 2022-05-09 17:17
As this is a duplicate of #744, I’ll close this issue.

**Closed as completed by Flakebi** 2022-05-09 17:17 UTC
