### ISSUE TITLE
Dotnet dont work

### ISSUE THREAD

**Issue by Tentoxa** [Splamy/TS3AudioBot#812] opened 2020-06-21 19:36 UTC
**Describe the problem**
When i start the Bot the Message: 
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      3.1.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.2.0&arch=x64&rid=debian.9-x64

When i go to this website there is this Message:
This release has reached end of life

**To Reproduce**
when i make dotnet TS3AudioBot.dll

**System Information**
- **Debian 9**: (Ubuntu 16.04, Debian 8, Arch, etc)  
  
- **I use Dotnet version 3.1.301  **: (`mono -V`)  
  
- **dotnet TS3AudioBot.dll
**: (or on prebuilt: `mono TS3AudioBot.exe -V`)  
  
(If all fields in the TS3AudioBot log header are correctly filled you can
alternatively just post the header here.)

**Additional Logs, Exceptions, etc**
When applicable try to add relevant log excerpts here.

```
Put logs or code in triple backticks like here to properly format it.
```

**Comment by Flakebi** [comment] 2020-06-21 21:09
Which version did you download?
If you have dotnet core 3.1, you should download the 3.1 version. You can also download the native linux version (marked as experimental) here: https://splamy.de/TSAudioBot/Home

**Comment by Flakebi** [comment] 2020-06-29 19:57
If the problem is still there, please comment or reopen this issue.

**Closed by Flakebi** 2020-06-29 19:57 UTC
