### ISSUE TITLE
[Help] Running it

### ISSUE THREAD

**Issue by regendare** [Splamy/TS3AudioBot#55] opened 2017-03-19 19:14 UTC
So i followed everything for the linux installation, and TS3Audiobot.exe isnt found?, how do i run it

**Comment by Splamy** [comment] 2017-03-20 02:00
what was the output of xbuild? Have you looked into TS3AudioBot/bin/Release ?

**Comment by regendare** [comment] 2017-03-20 15:11
My apologies, i have found it now thanks!, But now how do i set it's prefered username / bind to a specific server id / server port once it connects via serverquery

**Comment by Splamy** [comment] 2017-03-20 15:28
The current master/develop version does not connect via server query, but instead with a normal client.
The server address and port should have been asked at the first start of the bot. If you missed that you can still configure it in the `configTS3AudioBot.cfg` near the `TS3AudioBot.exe`.
The settings are called `QueryConnection::host` and `QueryConnection::port`. (Yeah I know somewhat misleading due to backwards compatibility).
Username cannot be set yet, I will add it in the future.

**Comment by regendare** [comment] 2017-03-20 15:29
Ohh, okay thank you so much!

**Comment by regendare** [comment] 2017-03-20 15:49
I keep running into an issue, where the song wont be played. The bot does have full admin access. There is no audio comming out

**Comment by Splamy** [comment] 2017-03-20 15:55
Have you tried other songs? Is there any additional info?

**Comment by regendare** [comment] 2017-03-20 16:03
Heres a log after restarting an playing a song, i have tried many songs before this all comming to the same conclusion.
```
[09:01:17]   Info: [============ TS3AudioBot started =============]
[09:01:17]   Info: [=== Date:           Monday, March 20, 2017 ===]
[09:01:17]   Info: [=== Time:                       9:01:17 AM ===]
[09:01:17]   Info: [==============================================]
[09:01:17]   Info: [============ Initializing Commands ===========]
[09:01:17]   Info: [============ Initializing Modules ============]
[09:01:18]   Info: [=========== Initializing Factories ===========]
[09:01:18]   Info: [=========== Registering callbacks ============]
[09:01:18]   Info: [================= Finalizing =================]
[09:01:18]   Info: [============== Connected & Done ==============]
[09:01:23]  Debug: MB Got message from Regendare: !play [URL]https://www.youtube.com/watch?v=ySTQk6updjQ[/URL]
[09:01:23]  Debug: SM User Regendare created session with the bot
[09:01:24]  Debug: AF stop old
[09:01:24]  Debug: AF ar start: Youtube ID:ySTQk6updjQ
[09:01:24]  Debug: AF set volume: 10
[09:01:25]Warning: SongStoppedHook could not play Next: No next song could be played
```

**Comment by Splamy** [comment] 2017-03-20 16:28
can you for example try this:
http://cdn.akamai.steamstatic.com/steamcommunity/public/assets/minigame/towerattack/sfx/backgroundtrack2.mp3

**Comment by regendare** [comment] 2017-03-20 17:00
That did not work either, it gave me the some warning.

**Comment by Splamy** [comment] 2017-03-21 11:18
Since my bot doesn't log any useful data I can just poke in the dark what the cause for this mysterious problem is.
I will push a new branch called `buggy` shortly with a few new debug log calls.
And said I really dont have any idea what it could be, so if this persists, the easiest thing might be that I connect to your server and debug my bot instance to see if it's the server configuration, the vserver or something extern.

**Comment by lima12** [comment] 2017-04-01 20:25
sorry for being a noob ! but after i config the bot and run it , it connect to my ts3 server and INSTANTLY disconnect ! im using window

**Comment by Splamy** [comment] 2017-07-04 21:36
A new setting allowes to stream to the current channel with normal voice mode, see [here](https://github.com/Splamy/TS3AudioBot/issues/62#issuecomment-311783984).
Since the problem with this issue was on the server side and not on the bot I will close this issue. If you got any new problems feel free to open another issue instead, or look for an open one to reduce duplicates.

**Closed by Splamy** 2017-07-04 21:36 UTC
Labels: question, waiting for response
