### ISSUE TITLE
Song name

### ISSUE THREAD

**Issue by PortStone** [Splamy/TS3AudioBot#237] opened 2018-04-20 18:47 UTC
Hey,

if I type in !song it just says the link it streams:

<20:42:23> "AudioBot": http://stream01.iloveradio.de/iloveradio1.mp3

But SinusBot actually says the name: 
<20:43:46> "Musikbot #1": Now playing: AXWELL INGROSSO - DREAMER

Also on SinusBot you can select the actual song name as description and you can announce songs.

Could you add those features as well? I don't really like SinusBot (not open source and so on)

**Comment by Splamy** [comment] 2018-04-21 00:53
Yes, this is planned.

Since this is a duplicate of #200 please continue further discussion there.

**Closed by Splamy** 2018-04-21 00:53 UTC

**Comment by lgund** [comment] 2019-08-10 08:18
Is here now more informations?

**Comment by Splamy** [comment] 2019-08-10 11:18
As you can see in #200, yes everything basically works. There might still pop up some weird warnings and stuff but I hope to patch everything out until relese.
