### ISSUE TITLE
Question about connecting to a server

### ISSUE THREAD

**Issue by Generalas** [Splamy/TS3AudioBot#782] opened 2020-04-25 16:31 UTC
When using function “ /bot/connect/to/{address}/{password} “ is it possible to specify the bots nickname on the server?

**Comment by Splamy** [comment] 2020-04-26 14:54
Duplicate of #360 see here for discussion / more details: https://github.com/Splamy/TS3AudioBot/issues/360#issuecomment-425404500

**Closed by Splamy** 2020-04-26 14:54 UTC
