### ISSUE TITLE
Webinterface

### ISSUE THREAD

**Issue by TomGamerTV** [Splamy/TS3AudioBot#416] opened 2018-10-28 13:14 UTC
Hello,

How do you add your own web interface to the TS3AudioBot?

**Comment by CookieCr2nk** [comment] 2018-10-28 13:37
You edith the config "ts3audiobot.toml" at the end of the menu you see [web.interface] you must only change the webinterface path.

**Comment by TomGamerTV** [comment] 2018-10-28 13:41
After that it is not connected to my web interface, right? Because you still have to adjust everything in the interface or right?

**Comment by TomGamerTV** [comment] 2018-10-28 16:12
For me this is always here: Error:
Error getting bot list
Info:

**Comment by DoktorDuckyy** [comment] 2018-10-29 11:12
First you have to create a API token and insert it in the Webinterface

**Comment by TomGamerTV** [comment] 2018-10-29 11:13
I did that. Only the web interface does not recognize the TS3AudioBot. All settings are correct!

**Comment by Splamy** [comment] 2018-11-12 10:13
So does the problem persist or did you guys get it running?
If the problem is solved, please close the issue.

**Closed** 2018-11-30 00:09 UTC
