### ISSUE TITLE
voiceactivation whispermode

### ISSUE THREAD

**Issue by officialtaxz2** [Splamy/TS3AudioBot#605] opened 2019-07-24 19:10 UTC
Is it possible to change the way how the bot is playing music ? So from voiceactivation to a permanent activation? Because after a song is finished u will get the whisper notification again Because the bot "stopps playing"  before the next song is starting.

**Comment by Splamy** [comment] 2019-07-25 16:44
Duplicate of #437 please continue further discussion there.

**Closed by Splamy** 2019-07-25 16:44 UTC
