### ISSUE TITLE
All Bot stopping Random.

### ISSUE THREAD

**Issue by Nevercold** [Splamy/TS3AudioBot#761] opened 2020-04-02 08:57 UTC
**Describe the bug**
In my Webinterface, i send an API-Request "/api/bot/list/". I check how many Bots are Online.
Now, random all Bots are Timeout/Disconnect/

**Version**

Version: 0.12.0-alpha.11
Branch: develop
CommitHash: f913536594129656f9758b4332555a207d9dc09c

**Platform**

Debian 10
Dotnet 3.1

**Log**
```
2020-04-01 21:20:02.4045| INFO||WebApi.ProcessApiV1Call ::ffff:IP Requested: /api/bot/list/
2020-04-01 21:25:02.3318| INFO||WebApi.ProcessApiV1Call ::ffff:IP Requested: /api/bot/list/
2020-04-01 21:28:02.8386| INFO|2|Ts3Client.TryReconnect Reconnect strategy for 'Timeout' has reached the end. Closing instance.
2020-04-01 21:28:02.8386| INFO|2|Bot.Dispose Bot (2) disconnecting.
2020-04-01 21:28:03.8386| INFO|4|Ts3Client.TryReconnect Reconnect strategy for 'Timeout' has reached the end. Closing instance.
2020-04-01 21:28:03.8386| INFO|4|Bot.Dispose Bot (4) disconnecting.
2020-04-01 21:28:04.3391| INFO|0|Ts3Client.TryReconnect Reconnect strategy for 'Timeout' has reached the end. Closing instance.
2020-04-01 21:28:04.3391| INFO|0|Bot.Dispose Bot (0) disconnecting.
2020-04-01 21:28:05.8387| INFO|1|Ts3Client.TryReconnect Reconnect strategy for 'Timeout' has reached the end. Closing instance.
2020-04-01 21:28:05.8387| INFO|3|Ts3Client.TryReconnect Reconnect strategy for 'Timeout' has reached the end. Closing instance.
2020-04-01 21:28:05.8387| INFO|1|Bot.Dispose Bot (1) disconnecting.
2020-04-01 21:28:05.8387| INFO|3|Bot.Dispose Bot (3) disconnecting.
2020-04-01 21:30:01.5664| INFO||WebApi.ProcessApiV1Call ::ffff:116.203.255.175 Requested: /api/bot/list/
2020-04-01 21:30:57.6390| INFO|6|Ts3Client.TryReconnect Reconnect strategy for 'Timeout' has reached the end. Closing instance.
2020-04-01 21:30:57.6390| INFO|6|Bot.Dispose Bot (6) disconnecting.
2020-04-01 21:35:02.4015| INFO||WebApi.ProcessApiV1Call ::ffff:IP Requested: /api/bot/list/
```

**Comment by Nevercold** [comment] 2020-04-02 10:11
I have Seen, a new Version has released.
I now have installed the .16 and Test ist again.

**Comment by Nevercold** [comment] 2020-04-03 15:12
With the new Version, the Bots timeout.

**Comment by Splamy** [comment] 2020-04-05 22:30
I heard of timeout problems a lot in the past, so I think this is also a duplicate of #748.
I seriously have no Idea what might cause this and am looking for it in the past weeks. I've also met with someone to get a special debug log, but it's huge and it takes time to go though and find possible issues.

**Closed by Splamy** 2020-04-05 22:30 UTC
