### ISSUE TITLE
add bot admin or something like that

### ISSUE THREAD

**Issue by 9ofe** [Splamy/TS3AudioBot#714] opened 2020-01-09 16:22 UTC
way to give someone access to commands like !play !stop !pause
for a specific bot {not all the bots} 

and thanks <3

**Comment by Flakebi** [comment] 2020-01-09 21:24
You can already do this in the `rights.toml` file with the bot matcher.
An example is here: https://github.com/Splamy/TS3AudioBot/wiki/Rights#example-1

**Comment by 9ofe** [comment] 2020-01-09 22:48
my suggest is adding this to the interface website :)

**Comment by Flakebi** [comment] 2020-01-10 17:44
Ah ok, at the moment it is not possible to add this easily because the permissions/rights are not accessible via the api (and the website is just a nice gui for the api).
But it is definitely planned to add this.

Configuring permissions on the website is already tracked in #651, so I’ll close this issue as a duplicate of the tracking issue.

**Closed by Flakebi** 2020-01-10 17:44 UTC
Labels: question
