### ISSUE TITLE
Search for youtube first result 

### ISSUE THREAD

**Issue by Eithan13** [Splamy/TS3AudioBot#311] opened 2018-06-25 16:13 UTC
Hi, 
Would it be possible to add the ability to search and play for the first youtube result when running something lilke 
!play author name of the song
It would be usefull !
Sorry if my post isn't at the right place, I'm not used to Github

**Comment by Eithan13** [comment] 2018-06-25 16:16
Also if it can automatically play next musics from a playlist link on youtube

**Comment by Splamy** [comment] 2018-06-25 17:38
I'd say this is a duplicate of #89

**Closed by Splamy** 2018-06-25 17:38 UTC
Labels: duplicate, enhancement
