### ISSUE TITLE
Private session

### ISSUE THREAD

**Issue by Skagoo** [Splamy/TS3AudioBot#62] opened 2017-04-07 00:15 UTC
First of all, I am very happy to see that this project is active.

Could you provide me with some explanation on the private session?
When I start a private session I assumed that when I play a song, only I would here it. Wat is currently happening is the following:

- !pm (response: hi <UserName>)
- <InPrivateSession> !play <Source> (response: starts playing to all channels)
- <InPrivateSession> !unsubscribe channel (response: stops playing in user's channel)
- <InPrivateSession> !subscribe (response: starts playing to me)
- <InPrivateSession> !next (response: starts playing next song to all channels)
    FYI: Same thing happens on auto play

So my question is how to properly get private sessions per user, and how to fix the "playing to all channels on next song" issue?

I'm going to need some custome changes anyways later on, so if I would find and reslove this issue, I will make a pull request if not solved already.

Thanks in advence.

**Comment by Splamy** [comment] 2017-04-07 00:39
Hey,
the public/private session system is only relevant for text messages to prevent spamming the global chat. Also together with that, there is a rights-system overhaul long due but this still has to to wait.

Regading the play: This is a desing decision but I'm also not completely happy with it. (IIRC there is another issue somewhere with a similar complaint)

The current system works like that: when you play something, the channel you are currently in will be _auto_-subscribed. When a new song starts (in this case with !next) all auto-subscriptions are dropped and the initiating channel will be auto-subsctibed again.
When you subscribe your channel via command, the channel gets subscribed permanently until you manually unsubscribe it at which it goes back to the auto-mode, being unsubscribed by default. This was designed to prevent the problem that once you subscribe manually you'd be stuck in always manually on or off.
The best solution would maybe be a `!unsubscribe channel reset` command but this seems very unintuitive

**Comment by JABirchall** [comment] 2017-05-30 15:44
Is it possible with teamspeaks networking to stream multiple diffrent private sessions?

**Comment by Splamy** [comment] 2017-05-30 20:32
Audiowise not, we tried to multiplex the audiostreams but it completly breaks the incomming audio. You will need two client instances.

**Comment by JABirchall** [comment] 2017-06-14 10:48
Ahh that sucks, I thought it would be cool to have multiple users listening to different music on the same bot.
Is it completely not possible to stream separate whispers with different audio sources.

**Comment by Splamy** [comment] 2017-06-28 20:44
There now is a new setting available on the dev branch
`AudioFramework::AudioMode=voice`
to tell the bot to use normal voice for playing.
(see [here](https://github.com/Splamy/TS3AudioBot/issues/84#issuecomment-311753043) for a few more details)

**Comment by Splamy** [comment] 2017-08-27 01:39
Since this issue is over a month old I will close it now. If you still have any problems feel free to reopen this or open a new issue.

**Closed by Splamy** 2017-08-27 01:39 UTC
Labels: enhancement, waiting for response
