### ISSUE TITLE
!history

### ISSUE THREAD

**Issue by robotrono** [Splamy/TS3AudioBot#138] opened 2017-10-27 09:37 UTC
When I write the command !history get this:

> Error: No matching function could be found

Its normal?

**Comment by Splamy** [comment] 2017-10-27 10:00
The command `!history` itself indeed has no function, it has plenty of subfunctions (as seen with `!help history`) but the error message is indeed strange. At least I have the same problem, so I think this should be fixed easily

**Comment by Splamy** [comment] 2017-10-27 15:10
Ok I found out why it happens, and it's kinda intended. Sooo "it's a feature not a bug" :P.
Reason why is because the `!history` matches to `!history "id" <x>` since the empty string after `!history` matches "id" because it is the shortest command. Id has two overloads, none of which match because they, again, get an empty string.
Nonetheless i'll try to see if I can get a better error response there.

**Closed** 2017-11-08 01:01 UTC
Labels: bug
