### ISSUE TITLE
ERROR: An item with the same key has already been added.

### ISSUE THREAD

**Issue by VerHext** [Splamy/TS3AudioBot#108] opened 2017-08-23 15:31 UTC
Often the bot shows the bot the lower error. I have not noticed any regularity. He just comes random. There is an error in the TS3AudioClient.

```

[11:28:59]  Error: Critical program failure!. Exception:
MSG: An item with the same key has already been added.
TYPE:ArgumentException
STACK:  at System.ThrowHelper.ThrowArgumentException (System.ExceptionResource resource) [0x0000b] in <a07d6bf484a54da2861691df910339b1>:0
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Insert (TKey key, TValue value, System.Boolean add) [0x0007c] in <a07d6bf484a54da2861691df910339b1>:0
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <a07d6bf484a54da2861691df910339b1>:0
  at TS3Client.Full.PacketHandler.AddOutgoingPacket (TS3Client.Full.OutgoingPacket packet, TS3Client.Full.PacketFlags flags) [0x00162] in <7d21a7e6606a421cb436be5d756ae485>:0
  at TS3Client.Full.PacketHandler.AddOutgoingPacket (System.Byte[] packet, TS3Client.Full.PacketType packetType) [0x00084] in <7d21a7e6606a421cb436be5d756ae485>:0
  at TS3Client.Full.PacketHandler.SendPing () [0x00000] in <7d21a7e6606a421cb436be5d756ae485>:0
  at TS3Client.Full.PacketHandler.ResendLoop () [0x000e0] in <7d21a7e6606a421cb436be5d756ae485>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <a07d6bf484a54da2861691df910339b1>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <a07d6bf484a54da2861691df910339b1>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <a07d6bf484a54da2861691df910339b1>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <a07d6bf484a54da2861691df910339b1>:0
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <a07d6bf484a54da2861691df910339b1>:0

Error call Stack:
Void <Main>b__0(System.Object, System.UnhandledExceptionEventArgs)@0 T:PacketHandler
[11:28:59]   Info: Exiting...
[11:28:59]Warning: Internal error (me==null)

```

**Comment by davlast** [comment] 2017-08-23 15:39
hi, fyi, i also get this error, when i restart the bot, i use `!quit force` to shut it down and then i try start it again i get this error, have to wait like 5 mins before i can connect it back to the server again

**Comment by Splamy** [comment] 2017-08-24 12:59
Yes this is bug with my ts3client implementation, I think this is related to #51 where packets get processed which should not be accepted.

**Comment by Splamy** [comment] 2017-08-25 18:40
Ok latest dev branch should have fixed that

**Comment by VerHext** [comment] 2017-09-09 08:46
Sorry but the bug isnt fixed. 

```
packetPingManager.Add(packet.PacketId, packet);
```
this code make the dupplicate key error.

**Comment by Splamy** [comment] 2017-09-09 15:25
Does this happen while running or rather only when starting the bot

**Comment by VerHext** [comment] 2017-09-09 17:24
- only by starting. If i connected to large Server...
- I use the latest develop branch. "19bf32"

**Comment by Splamy** [comment] 2017-09-11 03:10
Ok, pushed an update to the dev branch, this one should fix it for real since I removed the dictionary :P

**Comment by JABirchall** [comment] 2017-09-11 10:17
Would this also solve #51 or is that still a problem to be addressed?

**Comment by Splamy** [comment] 2017-09-11 10:26
Good thing you asked, I have looked into the "source code" of the server again to find out what exactly ther server allows and why.
In my client implementation I have set the decompression limit to 40000 because that is the limit that the server has when receiving packets from the client.
Apparently this does not apply the other way round. The client must accept way bigger packets.
I have raised the limit to 1024*1024, which is pretty large. The normal client accepts even bigger packets, but for now I think this is a fine limit for my client.
With this settings I can go to up to ~850 clients.
The problems here is simple. The stupid server sends a clientnotifyenter when a you join enters the server, this event conains _all_ clients in the current channel. Therefore this one packets dempressed size gets huuge. But it is still a valid packet.
Maybe I'll just make that variable setable so everyone can set its own safety threshold.

**Comment by JABirchall** [comment] 2017-09-11 11:55
Ok, So that was the fix i put in my self, but that also ran into the other issues of the array.copy in ts3crypt after a couple hours of running. Unless that is unrelated to the issue?

**Comment by Splamy** [comment] 2017-09-11 12:05
That is unrelated, I still dont know how wrong packets get accepted into the queue..
I also cant reproduce it at all even with 800 clients...

**Comment by JABirchall** [comment] 2017-09-11 12:06
Okay dokie.

**Comment by VerHext** [comment] 2017-09-12 12:05
The bot is no longer crashed, but it is not connected.

**Comment by Splamy** [comment] 2017-09-12 12:46
huh, strange, could you pm me your server version or address?

**Comment by Splamy** [comment] 2017-09-13 02:51
Ok the Bot now supports tsdns and even the new nickname lookups :D
let me know if eveything works
The commit is on the dev branch.
**NOTE**: this commit introduces a braking change, the `host` and `port` config entry have been merged to a new `address` field. You will have to reenter your connection details

**Comment by VerHext** [comment] 2017-09-13 12:30
It works. Thanks for this great update.

**Comment by Splamy** [comment] 2017-09-13 15:51
Nice, then I will close this issue

**Closed by Splamy** 2017-09-13 15:51 UTC
Labels: bug
