### ISSUE TITLE
Bot Crashed suddenly

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#533] opened 2019-03-30 15:59 UTC
The Bot crashed suddenly. We dont know to fix this

master 0.9

ubuntu 16.04 
Mono JIT compiler version 5.16.0.179 (tarball Thu Oct  4 10:29:10 UTC 2018)

**Log**
```
2019-03-30 16:35:39.3045| INFO|Bot.OnBotConnected Bot "111730191"(5) connected.
2019-03-30 16:35:39.5077|FATAL|Core.ExceptionHandler Critical program failure!
System.NullReferenceException: Object reference not set to an instance of an object
  at TS3AudioBot.Bot.TextCallback (System.Object sender, TS3Client.Messages.TextMessage textMessage) [0x00046] in <02bf89dd91ec4081b518b95e0a31bf9b>:0 
  at TS3AudioBot.Ts3Client.ExtendedTextMessage (System.Object sender, System.Collections.Generic.IEnumerable`1[T] eventArgs) [0x00045] in <02bf89dd91ec4081b518b95e0a31bf9b>:0 
  at TS3Client.Full.Ts3FullClient.InvokeEvent (TS3Client.LazyNotification lazyNotification) [0x0247d] in <c74fdd5163894bf0ac391fc5820b6273>:0 
  at TS3Client.DoubleThreadEventDispatcher.DispatchLoop () [0x00024] in <c74fdd5163894bf0ac391fc5820b6273>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x7f5d9ce52ef0 + 0x00095> in <3833a6edf2074b959d3dab898627f0ac>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) <0x7f5d9ce50cf0 + 0x001a2> in <3833a6edf2074b959d3dab898627f0ac>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x7f5d9ce50ca0 + 0x00016> in <3833a6edf2074b959d3dab898627f0ac>:0 
  at System.Threading.ThreadHelper.ThreadStart () <0x7f5d9ce53010 + 0x00020> in <3833a6edf2074b959d3dab898627f0ac>:0 
2019-03-30 16:35:39.5077| INFO|Core.Dispose TS3AudioBot shutting down.
2019-03-30 16:35:39.5077| INFO|Bot.Dispose Bot (0) disconnecting.
2019-03-30 16:35:39.5252| INFO|Bot.Dispose Bot (1) disconnecting.
2019-03-30 16:35:39.5444| INFO|Bot.Dispose Bot (2) disconnecting.
2019-03-30 16:35:39.5476| INFO|Bot.Dispose Bot (3) disconnecting.
2019-03-30 16:35:39.5633| INFO|Bot.Dispose Bot (4) disconnecting.
2019-03-30 16:35:39.5720| INFO|Bot.Dispose Bot (5) disconnecting.
2019-03-30 16:35:39.6702| INFO|WebServer.EnterWebLoop WebServer has closed
```

**Comment by Splamy** [comment] 2019-04-03 18:02
Duplicate of #532 please continue further discussion there.

**Closed by Splamy** 2019-04-03 18:02 UTC
